gazebo_ros_control:
  pid_gains:
    joint1: { p: 100.0,  d: 0.0, i: 0.0 }
    joint2: { p: 100.0,  d: 0.0, i: 0.0 }
    joint3: { p: 100.0,  d: 0.0, i: 0.0 }
    joint4: { p: 100.0,  d: 0.0, i: 0.0 }
    joint5: { p: 100.0,  d: 0.0, i: 0.0 }
    joint6: { p: 100.0,  d: 0.0, i: 0.0 }